/**
 *
 * DTO contracts — category management
 *
 * Tables sources :
 *   - cs_faq (parent_type='category')   (module ac_faq polymorphique)
 *   - cs_faq_lang                       (id_lang, question, answer)
 *   - cs_category_cms                   (pivot N-N id_category ↔ id_cms, position, module ac_cmscategoryextra)
 *
 * The 'footer' description reuses the native field
 * ps_category_lang.description (no new column).
 */

/** Une question/réponse FAQ attachée à une catégorie. */
export interface CategoryFaq {
  /** undefined = new row to create server-side */
  id?: number
  position: number
  active: boolean
  question: string
  /** HTML generated by the WYSIWYG */
  answer: string
}

/** A blog article (ps_cms) linked to a category via the pivot. */
export interface LinkedBlogPost {
  /** id_cms */
  id: number
  /** position in the related articles carousel */
  position: number
  title: string
  slug: string
  datePublished?: string | null
  cover?: string | null
}

/** Autocomplete result from the /api/bo/cms/search endpoint. */
export interface CmsSearchResult {
  id: number
  title: string
  slug: string
  datePublished?: string | null
  active: boolean
}
