/**
 *
 * Direct database helpers for /api/academy/* — no external webservice calls
 * PrestaShop » 2026-04-22. Tables :
 * - cs_academy_qa            (student Q&A + AI response + upvotes)
 * - cs_academy_mentor_quote  (contextual insight per lesson)
 * - cs_academy_suggestion    (suggested question per lesson, AI-generated)
 *   - cs_academy_student       (jointure pseudo + avatar)
 *
 * Single-tenant: Academy runs only on the main instance, not
 * on other tenant instances → targets PostgreSQL `ac_hub` schema
 * `cs_main` via `usePocPg()` (chantier #38/#44 cutover PG-only).
 */

import { sql } from 'drizzle-orm'
import { usePocPg } from '../db/drizzle-pg'

export interface MentorQuote {
  quote: string | null
  mentor: string | null
  source: string | null
}

/** Pensée contextuelle d'un mentor pour une leçon donnée. */
export async function getMentorQuote(moduleSlug: string, lessonIndex: number): Promise<MentorQuote> {
  if (!moduleSlug) return { quote: null, mentor: null, source: null }
  const result = await usePocPg().execute(sql`
    SELECT quote, mentor, source
      FROM cs_main.cs_academy_mentor_quote
     WHERE module_slug = ${moduleSlug}
       AND lesson_index = ${lessonIndex}
     LIMIT 1
  `)
  const row = (result as any[])[0] ?? null
  return {
    quote: row?.quote || null,
    mentor: row?.mentor || null,
    source: row?.source || null,
  }
}

export interface QaRow {
  id_qa: number
  module_slug: string
  lesson_index: number
  id_student: number
  question: string
  ai_answer: string | null
  status: string
  upvotes: number
  date_add: string
  date_upd: string
  pseudo: string | null
  avatar_url: string | null
}

/**
 * Published Q&A for a module (and optionally a specific lesson),
 * joins cs_academy_student for username + avatar.
 */
export async function getQaForModule(
  moduleSlug: string,
  lessonIndex: number | null,
  status = 'published',
): Promise<QaRow[]> {
  if (!moduleSlug) return []
  const lessonClause = lessonIndex !== null
    ? sql`AND qa.lesson_index = ${lessonIndex}`
    : sql``
  const result = await usePocPg().execute(sql`
    SELECT qa.id_qa, qa.module_slug, qa.lesson_index, qa.id_student,
           qa.question, qa.ai_answer, qa.status, qa.upvotes,
           qa.date_add, qa.date_upd,
           s.pseudo, s.avatar_url
      FROM cs_main.cs_academy_qa qa
 LEFT JOIN cs_main.cs_academy_student s ON s.id_student = qa.id_student
     WHERE qa.module_slug = ${moduleSlug}
       AND qa.status = ${status}
       ${lessonClause}
     ORDER BY qa.upvotes DESC, qa.date_add DESC
  `)
  return (result as unknown as QaRow[]) ?? []
}

/** Question suggérée pour une leçon, ou null si absente. */
export async function getSuggestion(moduleSlug: string, lessonIndex: number): Promise<string | null> {
  if (!moduleSlug) return null
  const result = await usePocPg().execute(sql`
    SELECT question FROM cs_main.cs_academy_suggestion
     WHERE module_slug = ${moduleSlug}
       AND lesson_index = ${lessonIndex}
     LIMIT 1
  `)
  const row = (result as unknown as { question: string }[])[0] ?? null
  return row?.question || null
}

/** UPSERT a suggestion (generated by the AI queue). */
export async function upsertSuggestion(
  moduleSlug: string,
  lessonIndex: number,
  question: string,
): Promise<void> {
  await usePocPg().execute(sql`
    INSERT INTO cs_main.cs_academy_suggestion (module_slug, lesson_index, question, date_add, date_upd)
    VALUES (${moduleSlug}, ${lessonIndex}, ${question}, NOW(), NOW())
    ON CONFLICT (module_slug, lesson_index) DO UPDATE SET
      question = EXCLUDED.question,
      date_upd = NOW()
  `)
}

/**
 * Increments upvotes on a published Q&A. Returns the new total or null
 * if the Q&A doesn't exist / isn't published.
 */
export async function incrementQaUpvote(idQa: number): Promise<number | null> {
  if (idQa <= 0) return null
  const d = usePocPg()
  const result = await d.execute(sql`
    SELECT id_qa, upvotes, status FROM cs_main.cs_academy_qa WHERE id_qa = ${idQa} LIMIT 1
  `)
  const qa = (result as unknown as { id_qa: number; upvotes: number; status: string }[])[0] ?? null
  if (!qa || qa.status !== 'published') return null
  await d.execute(sql`UPDATE cs_main.cs_academy_qa SET upvotes = upvotes + 1 WHERE id_qa = ${idQa}`)
  return Number(qa.upvotes) + 1
}

/** Push réponse IA + change status d'une Q&A (appelé par la queue IA). */
export async function updateQaAiAnswer(
  idQa: number,
  aiAnswer: string,
  status: 'pending' | 'published' | 'flagged' = 'published',
): Promise<{ ok: boolean; error?: string }> {
  if (idQa <= 0) return { ok: false, error: 'id_qa requis' }
  const d = usePocPg()
  const result = await d.execute(sql`
    SELECT id_qa FROM cs_main.cs_academy_qa WHERE id_qa = ${idQa} LIMIT 1
  `)
  const exists = (result as unknown as { id_qa: number }[])[0] ?? null
  if (!exists) return { ok: false, error: 'Q&A introuvable' }
  await d.execute(sql`
    UPDATE cs_main.cs_academy_qa
       SET ai_answer = ${aiAnswer},
           status = ${status},
           date_upd = NOW()
     WHERE id_qa = ${idQa}
  `)
  return { ok: true }
}
