/**
 *
 * cs_giftcard facade — gift card sales. Multi-tenant via client_id.
 *
 * Public code format XXXX-XXXX-XXXX (12 hex upper) — non-sequential, non-
 * enumerable, generated by crypto.randomBytes to resist brute-force attacks.
 *
 * Default validity: 1 year (expires_at). Complies with legal minimums.
 */

import { sql } from 'drizzle-orm'
import { randomBytes } from 'node:crypto'
import { usePocPg } from '~/server/db/drizzle-pg'

export type GiftcardStatus = 'pending' | 'paid' | 'sent' | 'redeemed' | 'expired' | 'cancelled'
export type GiftcardDeliveryMode = 'pdf' | 'email' | 'both'

export interface GiftcardRow {
  id_giftcard: number
  client_id: string
  code: string
  amount_cents: number
  balance_cents: number
  currency: string
  status: GiftcardStatus
  delivery_mode: GiftcardDeliveryMode
  purchaser_name: string
  purchaser_email: string
  recipient_name: string | null
  recipient_email: string | null
  personal_message: string | null
  scheduled_send_at: string | null
  id_order: number | null
  pdf_token: string
  purchased_at: string | null
  sent_at: string | null
  redeemed_at: string | null
  id_redemption_order: number | null
  expires_at: string
  date_add: string
  date_upd: string
}

const HEX_ALPHABET = '0123456789ABCDEF'

/** Génère un code XXXX-XXXX-XXXX (12 hex upper, ~10^14 combinaisons). */
export function generateGiftcardCode(): string {
  const bytes = randomBytes(6)
  const chars: string[] = []
  for (let i = 0; i < 12; i++) {
    const byteIdx = Math.floor(i / 2)
    const nibble = (i % 2 === 0) ? (bytes[byteIdx] >> 4) : (bytes[byteIdx] & 0x0f)
    chars.push(HEX_ALPHABET[nibble])
  }
  return `${chars.slice(0, 4).join('')}-${chars.slice(4, 8).join('')}-${chars.slice(8, 12).join('')}`
}

export function generatePdfToken(): string {
  return randomBytes(24).toString('hex')
}

export interface CreateGiftcardInput {
  clientId: string
  amountCents: number
  deliveryMode: GiftcardDeliveryMode
  purchaserName: string
  purchaserEmail: string
  recipientName?: string | null
  recipientEmail?: string | null
  personalMessage?: string | null
  scheduledSendAt?: Date | null
  validityDays?: number
}

export interface CreateGiftcardResult {
  idGiftcard: number
  code: string
  pdfToken: string
  expiresAt: Date
}

/**
 * Creates a gift card in `pending` status (awaiting payment). The code
 * is regenerated up to 5 times in case of unlikely collision
 * (10^14 combinations → collision almost impossible but we protect against it).
 */
export async function createGiftcard(input: CreateGiftcardInput): Promise<CreateGiftcardResult> {
  if (input.amountCents < 1000 || input.amountCents > 50000) {
    throw new Error('amount_cents must be in [1000, 50000]')
  }
  const validityDays = input.validityDays ?? 365
  const expiresAt = new Date(Date.now() + validityDays * 24 * 60 * 60 * 1000)
  const pdfToken = generatePdfToken()

  let lastErr: any
  for (let attempt = 0; attempt < 5; attempt++) {
    const code = generateGiftcardCode()
    try {
      const result = await usePocPg().execute<any>(sql`
        INSERT INTO cs_main.cs_giftcard
          (client_id, code, amount_cents, balance_cents, currency, status,
           delivery_mode, purchaser_name, purchaser_email,
           recipient_name, recipient_email, personal_message, scheduled_send_at,
           pdf_token, expires_at, date_add, date_upd)
        VALUES (
          ${input.clientId}, ${code}, ${input.amountCents}, ${input.amountCents},
          'EUR', 'pending', ${input.deliveryMode},
          ${input.purchaserName}, ${input.purchaserEmail.toLowerCase()},
          ${input.recipientName ?? null}, ${input.recipientEmail ? input.recipientEmail.toLowerCase() : null},
          ${input.personalMessage ?? null}, ${input.scheduledSendAt ?? null},
          ${pdfToken}, ${expiresAt}, NOW(), NOW()
        )
        RETURNING id_giftcard
      `)
      const row = ((result as any) as any[])[0]
      return {
        idGiftcard: Number(row.id_giftcard),
        code,
        pdfToken,
        expiresAt,
      }
    } catch (err: any) {
      // Code unique constraint violation → retry
      if (err?.code === '23505' || /uk_giftcard_client_code/.test(String(err?.message || ''))) {
        lastErr = err
        continue
      }
      throw err
    }
  }
  throw lastErr ?? new Error('giftcard code collision after 5 attempts')
}

export interface GetByCodeResult {
  giftcard: GiftcardRow | null
  /** Etat normalisé pour affichage front (sans leak de raisons précises). */
  state: 'valid' | 'invalid' | 'expired' | 'redeemed' | 'pending'
}

export async function getGiftcardByCode(clientId: string, code: string): Promise<GetByCodeResult> {
  const normalized = code.trim().toUpperCase().replace(/[^0-9A-F-]/g, '')
  if (!normalized) return { giftcard: null, state: 'invalid' }

  const result = await usePocPg().execute<any>(sql`
    SELECT id_giftcard, client_id, code, amount_cents, balance_cents, currency,
           status, delivery_mode, purchaser_name, purchaser_email,
           recipient_name, recipient_email, personal_message, scheduled_send_at,
           id_order, pdf_token, purchased_at, sent_at, redeemed_at,
           id_redemption_order, expires_at, date_add, date_upd
      FROM cs_main.cs_giftcard
     WHERE client_id = ${clientId}
       AND lower(code) = lower(${normalized})
     LIMIT 1
  `)
  const row = ((result as any) as any[])[0]
  if (!row) return { giftcard: null, state: 'invalid' }

  const card = row as GiftcardRow
  const now = Date.now()
  const expires = new Date(card.expires_at).getTime()
  if (card.status === 'redeemed') return { giftcard: card, state: 'redeemed' }
  if (card.status === 'pending') return { giftcard: card, state: 'pending' }
  if (card.status === 'cancelled') return { giftcard: card, state: 'invalid' }
  if (now > expires || card.status === 'expired') return { giftcard: card, state: 'expired' }
  return { giftcard: card, state: 'valid' }
}

export async function getGiftcardByPdfToken(token: string): Promise<GiftcardRow | null> {
  const result = await usePocPg().execute<any>(sql`
    SELECT id_giftcard, client_id, code, amount_cents, balance_cents, currency,
           status, delivery_mode, purchaser_name, purchaser_email,
           recipient_name, recipient_email, personal_message, scheduled_send_at,
           id_order, pdf_token, purchased_at, sent_at, redeemed_at,
           id_redemption_order, expires_at, date_add, date_upd
      FROM cs_main.cs_giftcard
     WHERE pdf_token = ${token}
     LIMIT 1
  `)
  const row = ((result as any) as any[])[0]
  return (row ?? null) as GiftcardRow | null
}
