/** @author CodeMyShop <noreply@codemyshop.com> | @copyright 2026 CodeMyShop | @license   AGPL-3.0-or-later */

/**
 * Shared helpers for building product SEO URLs and WebP images.
 * Used by promotions / bestsellers / new-products / search / suggest.
 */

/**
 * URL SEO produit : /produit/{id}-{slug}
 * PS redirige naturellement /produit/{id} via middleware legacy-redirects
 * toward the siloed structure. The slug in the URL enhances SEO without requiring
 * a dedicated route.
 */
export function buildProductUrl(id: number, linkRewrite?: string | null): string {
  if (linkRewrite && linkRewrite.length > 0) {
    return `/produit/${id}-${linkRewrite}`
  }
  return `/produit/${id}`
}

/**
 * Static SEO WebP image URL — served directly by nginx from
 * pre-generated by the `ac_productcovergen` module:
 *
 *   /img/p/{digits(id_image)}/{id_image}-{slug}-{width}.webp
 *
 * Sizes {cart|home|medium|large} are mapped to responsive breakpoints
 * 400/600/800/1200 (aligned with buildProductImage → src/srcset).
 * `clientId` preserved for signature backward compatibility (unused for static URLs).
 */
const SIZE_TO_WIDTH: Record<string, number> = {
  cart:   400,
  home:   600,
  medium: 800,
  large:  1200,
}

function normalizeSlug(linkRewrite?: string | null): string {
  return (linkRewrite && linkRewrite.length > 0)
    ? linkRewrite
        .normalize('NFD')
        .replace(/[̀-ͯ]/g, '')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 60) || 'product'
    : 'product'
}

export function buildImageUrl(
  imageId: number,
  size: 'home' | 'cart' | 'medium' | 'large' = 'large',
  linkRewrite?: string | null,
  _clientId?: string,
): string | undefined {
  if (!imageId || imageId <= 0) return undefined
  const width = SIZE_TO_WIDTH[size] ?? 1200
  const digits = String(imageId).split('').join('/')
  const slug = normalizeSlug(linkRewrite)
  return `/img/p/${digits}/${imageId}-${slug}-${width}.webp`
}

/**
 * Responsive multi-size srcset — concatenation of 4 static WebP variants
 * pre-generated by the module. Lets the browser choose the
 * optimal size based on viewport (critical for mobile LCP).
 */
export function buildImageSrcset(
  imageId: number,
  linkRewrite?: string | null,
): string | undefined {
  if (!imageId || imageId <= 0) return undefined
  const digits = String(imageId).split('').join('/')
  const slug = normalizeSlug(linkRewrite)
  return [400, 600, 800, 1200]
    .map((w) => `/img/p/${digits}/${imageId}-${slug}-${w}.webp ${w}w`)
    .join(', ')
}
