/** @author CodeMyShop <noreply@codemyshop.com> | @copyright 2026 CodeMyShop | @license   AGPL-3.0-or-later */

/**
 * Generates a static CSS file from ThemeDbData.
 *
 * This file is the server-side mirror of useClientTheme.ts:
 * it produces exactly the same CSS variables, but as
 * a static file imported in the Nuxt build (zero JS runtime for the visitor).
 *
 * The Builder continues to use :style binding for live preview.
 * On "Save" click, sync.put.ts calls writeThemeCss() to freeze
 * the variables in clients/{tenant}/assets/theme-vars.css.
 *
 * Source of truth: cs_theme (DB-First). This CSS file is a
 * derived artifact, never edited manually.
 */
import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { generateColorScale } from '~/utils/colorShades'

// ── Maps identiques à useClientTheme.ts ─────────────────────────────────

const RADIUS_MAP: Record<string, { btn: string; card: string; input: string }> = {
  none: { btn: '0',       card: '0',       input: '0' },
  sm:   { btn: '0.25rem', card: '0.375rem', input: '0.375rem' },
  md:   { btn: '0.5rem',  card: '0.5rem',   input: '0.5rem' },
  lg:   { btn: '0.5rem',  card: '0.75rem',  input: '0.5rem' },
  full: { btn: '9999px',  card: '1rem',     input: '9999px' },
}

const CONTENT_WIDTH_MAP: Record<string, string> = {
  '6xl': '72rem',
  '7xl': '80rem',
  '8xl': '90rem',
  full:  '100%',
}

// ── Types (même structure que useThemeDb.ts) ─────────────────────────────

interface ThemeColors {
  primary: string
  secondary?: string | null
  background?: string | null
  foreground?: string | null
  muted?: string | null
  headerBg?: string | null
  footerBg?: string | null
  topBarBg?: string | null
  topBarText?: string | null
}

interface ThemeTypography {
  fontFamily?: string | null
  fontUrl?: string | null
  baseFontSize?: string | null
}

interface ThemeUi {
  borderRadius?: string
  contentWidth?: string | null
  shadow?: boolean
}

export interface ThemeCssInput {
  colors: ThemeColors
  typography?: ThemeTypography
  ui?: ThemeUi
}

// ── Génération CSS ──────────────────────────────────────────────────────

/**
 * Generates complete CSS content (string) from theme data.
 * Produces the same variables as useClientTheme.themeStyles.
 */
export function generateThemeCssContent(theme: ThemeCssInput): string {
  const lines: string[] = [
    '/* Auto-generated by ac_builder — DO NOT EDIT MANUALLY */',
    '/* Source of truth: cs_theme (DB-First) */',
    '',
  ]

  const vars: string[] = []

  // ── Couleur primaire : palette 50→900 ─────────────────────────────
  if (theme.colors.primary) {
    const scale = generateColorScale(theme.colors.primary)
    for (const [shade, value] of Object.entries(scale)) {
      const key = shade === 'DEFAULT' ? '--color-primary' : `--color-primary-${shade}`
      vars.push(`  ${key}: ${value};`)
    }
  }

  // ── Couleur secondaire : palette 50→900 ───────────────────────────
  if (theme.colors.secondary) {
    const scale = generateColorScale(theme.colors.secondary)
    for (const [shade, value] of Object.entries(scale)) {
      const key = shade === 'DEFAULT' ? '--color-secondary' : `--color-secondary-${shade}`
      vars.push(`  ${key}: ${value};`)
    }
  }

  // ── Tokens simples ────────────────────────────────────────────────
  if (theme.colors.background)  vars.push(`  --color-background: ${theme.colors.background};`)
  if (theme.colors.foreground)  vars.push(`  --color-foreground: ${theme.colors.foreground};`)
  if (theme.colors.muted)       vars.push(`  --color-muted: ${theme.colors.muted};`)
  if (theme.colors.headerBg)    vars.push(`  --color-header-bg: ${theme.colors.headerBg};`)
  if (theme.colors.footerBg)    vars.push(`  --color-footer-bg: ${theme.colors.footerBg};`)
  if (theme.colors.topBarBg)    vars.push(`  --color-topbar-bg: ${theme.colors.topBarBg};`)
  if (theme.colors.topBarText)  vars.push(`  --color-topbar-text: ${theme.colors.topBarText};`)

  // ── Typographie ───────────────────────────────────────────────────
  if (theme.typography?.fontFamily)   vars.push(`  --font-family: ${theme.typography.fontFamily};`)
  if (theme.typography?.baseFontSize) vars.push(`  --font-size-base: ${theme.typography.baseFontSize};`)

  // ── Border radius of interactive elements ────────────────────────────────
  const radius = theme.ui?.borderRadius ?? 'md'
  const r = RADIUS_MAP[radius] ?? RADIUS_MAP.md
  vars.push(`  --radius-btn: ${r.btn};`)
  vars.push(`  --radius-card: ${r.card};`)
  vars.push(`  --radius-input: ${r.input};`)

  // ── Width of the center column ──────────────────────────────────
  const cw = theme.ui?.contentWidth ?? '6xl'
  vars.push(`  --content-max-w: ${CONTENT_WIDTH_MAP[cw] ?? '72rem'};`)

  // ── :root block ───────────────────────────────────────────────────
  lines.push(':root {')
  lines.push(...vars)
  lines.push('}')
  lines.push('')

  // ── Shadow opt-out ────────────────────────────────────────────────
  if (theme.ui?.shadow === false) {
    lines.push('.theme-no-shadow,')
    lines.push('.theme-no-shadow * {')
    lines.push('  box-shadow: none !important;')
    lines.push('}')
    lines.push('')
  }

  // ── Google Fonts @import (anti-FOUT) ──────────────────────────────
  // Placed at the end of the file because @import in :root is not valid.
  // The browser loads the font as soon as CSS is parsed, before JS.
  // Note: @import at the beginning of the file would be more standard, but
  // Nuxt concatenates CSS in the bundle → order is guaranteed.
  if (theme.typography?.fontUrl) {
    lines.unshift(`@import url('${theme.typography.fontUrl}');`)
    lines.unshift('')
  }

  return lines.join('\n')
}

/**
 * Writes the theme-vars.css file for a given tenant.
 *
 * Resolved path:
 *   - Monorepo (dev/preprod) : clients/{clientId}/assets/theme-vars.css
 *   - VPS client (env NUXT_THEME_CSS_DIR) : {NUXT_THEME_CSS_DIR}/theme-vars.css
 */
export function writeThemeCss(clientId: string, theme: ThemeCssInput): void {
  const css = generateThemeCssContent(theme)

  const envDir = process.env.NUXT_THEME_CSS_DIR
  let targetDir: string

  if (envDir) {
    targetDir = envDir
  } else {
    // Monorepo : résoudre depuis process.cwd() → clients/{clientId}/assets/
    targetDir = resolve(process.cwd(), 'clients', clientId, 'assets')
  }

  if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true })
  }

  const filePath = resolve(targetDir, 'theme-vars.css')
  writeFileSync(filePath, css, 'utf-8')
}
