/**
 *
 * useI18nHead — injects <link rel="alternate" hreflang="..."/> into the
 * <head> for all active languages + x-default, based on the current URL.
 *
 * Usage: call in a layout (or via a global Nuxt plugin) so that
 * each page automatically exposes its language variants to Google.
 *
 * Canonical = FR version (without prefix). Alternates are generated by
 * translating the first segment via ROOT_TRANSLATIONS. Internal slugs
 * (e.g., 'fruit-sec') can be enriched by the page (override siloHreflang)
 * if the API response provides a different slug_lang.
 */
import { localizeRootSegment } from '~/utils/locale-route-roots'

export function useI18nHead() {
  const route = useRoute()
  const config = useRuntimeConfig()
  const base = ((config.public as any).psFrontUrl as string || '').replace(/\/$/, '')
  const locales: string[] = ((config.public as any).i18nLocales as string[]) || ['en']
  const LOCALE_PREFIX_RE = new RegExp(`^/(${locales.join('|')})(?:/|$)`)

  /** Path canonical (FR, sans préfixe lang). */
  const canonicalPath = computed<string>(() => {
    const p = route.path || '/'
    const m = p.match(LOCALE_PREFIX_RE)
    if (!m) return p
    const withoutLang = '/' + p.slice(m[0].length)
    // Retranslate the first segment to canonical FR if it's a translation
    // (ex: /en/wholesaler/fruit-sec/ → canonical /grossiste/fruit-sec/)
    // Simple implementation: leave as-is. The page component can
    // override via setI18nHead() if it needs the true canonical.
    return withoutLang
  })

  /** Generated alternates: one per supported ISO + x-default. */
  const alternates = computed(() => {
    const cPath = canonicalPath.value
    const links: Array<{ rel: string; hreflang: string; href: string }> = []

    // FR canonical
    links.push({ rel: 'alternate', hreflang: 'fr', href: `${base}${cPath}` })

    // Other languages — localized path with /:lang/ + translated root
    for (const iso of locales) {
      const firstSlash = cPath.indexOf('/', 1)
      const firstSeg = firstSlash > 0 ? cPath.slice(1, firstSlash) : cPath.slice(1)
      const rest = firstSlash > 0 ? cPath.slice(firstSlash) : ''
      const translatedRoot = localizeRootSegment(firstSeg, iso)
      const localizedPath = firstSeg
        ? `/${iso}/${translatedRoot}${rest}`
        : `/${iso}`
      links.push({ rel: 'alternate', hreflang: iso, href: `${base}${localizedPath}` })
    }

    // x-default → FR
    links.push({ rel: 'alternate', hreflang: 'x-default', href: `${base}${cPath}` })

    return links
  })

  useHead({
    link: () => alternates.value,
  })

  return { canonicalPath, alternates }
}
